### ISSUE TITLE
[Opinion] I dont really like food bar texture

### ISSUE THREAD

**Issue by MbtMarco** [GabrielDja/GUI-SimpleStylized#18]
(Close this if u aren't going to change that, its just a personal opinion, btw i love your texture pack)

**Comment by MbtMarco** [comment]
I think it doesn't match the style of Minecraft. It's too cartoony for my preference (Dont hate me :P)

**Comment by GabrielDja** [comment]
Thank you for your opinion,
**To each his own, no problem :D**
I agree that it's very cartoony and I think I'll remove it in a future Update.

But I might add a configuration so that Users can customize the Resource Pack to their preference.
Example: To switch from Current Texture to Classic.

**Thanks a lot!**

**Comment by MbtMarco** [comment]
Thank you very much for your reply, then I think I will close this issue.
